backend:
  name: github
  repo: ajikameasane-eng/Website   # ğŸ‘ˆ repo cá»§a cáº­u
  branch: main
  open_authoring: true

media_folder: "uploads"          # nÆ¡i lÆ°u áº£nh upload
public_folder: "/uploads"

collections:
  - name: "stories"
    label: "Truyá»‡n"
    folder: "stories"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "TiÃªu Ä‘á»", name: "title", widget: "string" }
      - { label: "TÃ¡c giáº£", name: "author", widget: "string", default: "Asane" }
      - { label: "áº¢nh bÃ¬a", name: "cover", widget: "image" }
      - { label: "MÃ´ táº£", name: "description", widget: "text" }
      - { label: "Ná»™i dung", name: "body", widget: "markdown" }
